#!/bin/bash
#
# File: systemd-boot-snapshots
# Project Path: ./mkinitcpio/hooks/systemd-boot-snapshots
# Installation Path: /usr/lib/initcpio/hooks/systemd-boot-snapshots
#
# mkinitcpio hook for systemd-boot-snapshots
# Adds support for booting from BTRFS snapshots in systemd-boot

build() {
    # Add the required binaries to the initramfs
    add_binary "/usr/lib/systemd-boot-snapshots/systemd-boot-mount-snapshot-modules"
    add_binary "/usr/lib/systemd-boot-snapshots/systemd-boot-snapshots-notify"
    
    # Add the hook script to be executed during boot
    add_runscript
}

help() {
    cat <<HELPEOF
This hook adds support for booting from BTRFS snapshots in systemd-boot.
It allows mounting the parent volume for kernel modules and provides
desktop notifications when booting into snapshots.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
